# Generated by Django 5.1.4 on 2025-02-02 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catagory', '0002_remove_catagory_model_relation'),
        ('taskmodel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_model',
            name='catagory_name',
            field=models.ManyToManyField(to='catagory.catagory_model'),
        ),
    ]
