# Generated by Django 5.1.4 on 2025-02-02 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catagory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catagory_model',
            name='relation',
        ),
    ]
